apiVersion: apps/v1
kind: Deployment
metadata:
  name: teeapp
  labels:
    app: teeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teeapp
  template:
    metadata:
      labels:
        app: teeapp
    spec:
      containers:
        - name: teeapp
          image: 139883179438.dkr.ecr.us-east-1.amazonaws.com/teeapp:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080